### PR TITLE
Update resource paths

### PR DESCRIPTION
**Pull request by Favorlock**
Update ResouceManager and ResourceManagerLoader paths to be consistent with the Overlap2D editor.

### CODE REVIEW

**Comment by azakhary** [comment]
Wait, how was this working before? o_O

**Comment by Favorlock** [comment]
I was implementing the runtime as described by the wiki and I placed the orig folder within my assets folder and the other files where necessary and noticed that I was having to juggle files around because of the fact the paths were incorrect in the runtime. It's not that you couldn't get things to work, but the structure wasn't according to the editor, which from my understanding takes precedence for defining the structure the runtime reads from.

**Comment by Favorlock** [comment]
Is the editor contents intended to be added to the game projects assets folder so that it can be uploaded to a repo with the entire project or is it really intended that you only drag certain contents from the editor project whenever changes are made?

I was thinking that it would be convenient to use a file structure such that the entire editor project contents could be added to the core game project's assets. I'll elaborate with a visual.

content/
- orig/
- - <orig assets>
...
export/
scenes/
project.dt
project.pit

I think this structure would be good because it could differentiate the assets of the core project from the assets of the editor while still keeping the same structure.

**Comment by azakhary** [comment]
Will get back on this a bit later, but just to mention - you do not need to copy paste enything, Ctrl+E exports things from editor exporting only things needed. Going forward, we also have internal plugin, that we might share soon, that changes export behaviour to pack things smartly and aim for performance (like pack all animations and fonts and other assets in one pack, to avoid additional render calls)

**Comment by Favorlock** [comment]
Ah, ok. Going to close this pr for now then.

**Pull request closed without merging**
