### PR TITLE
Enable origin utilization in transform calculations

### PR DESCRIPTION
**Pull request by rolandoislas**
Backwards compatible. Defaults to false and uses (0,0) as origin.

### CODE REVIEW

**Comment by azakhary** [comment]
Could you elaborate a bit more on what issue this fixes? Or what does this add?

**Comment by rolandoislas** [comment]
Currently, when transforming a composite the origin is hard coded to (0,0). The boolean variable added to TransformComponent will now allow the settable origin to be used.

**Comment by azakhary** [comment]
But if you have to set that default anyway for **each** component, why not set directly originX originY values instead?

**Comment by rolandoislas** [comment]
For backwards compatibility. It's marked as a TODO. Really any implementation that would allow for values other than the hardcoded 0 would be nice.

**Comment by alexfacciorusso** [comment]
So guys, why isn't this or #108 accepted and merged?

**Pull request closed without merging**
