### PR TITLE
Update EntityFactory.java

### PR DESCRIPTION
**Pull request by Pretzel777**
Fix double loading of spriterAnimations.

### CODE REVIEW

**Comment by azakhary** [comment]
Hi, thanks for the pull request, could you please elaborate more on where the duplication is? I can see only one example of it. (int i = 0; i < vo.sSpriterAnimations.size(); i++) is unique. the previous one is Sprite not Spriter.

**Comment by Pretzel777** [comment]
Screen of prev not-fixed version http://take.ms/F4ITg

**Comment by azakhary** [comment]
Yep, I can see it now! Thanks! :)) Merging.

**Comment by azakhary** [comment]
(This will be on maven with next build)

**Comment by Pretzel777** [comment]
Glad to help :)

**Pull request merged**
