### PR TITLE
Fix origin and rotation of physics objects

### PR DESCRIPTION
**Pull request by acatinon**
When using images with physics component and try to apply forces on theirs bodies, I found that center of mass and rotation are not correct, as you can see below :

bug

I set the center of mass in the editor to be at the center of the balloon, but the force is applied at the left bottom corner.

With the fix it looks better :

fix

### CODE REVIEW

**Comment by azakhary** [comment]
this seems right, going to test/merge tomorrow.

**Comment by olipoh** [comment]
Hi,

no it doesn't work. Here are 2 videos:

PR69 which fixes the rotation problem of images without physics but doesn't fix the center of max problem.

PR87 which is your fix. As you can see, it just cancels the PR69 fix.
[PR69-87.zip](https://github.com/UnderwaterApps/overlap2d-runtime-libgdx/files/139485/PR69-87.zip)

**Comment by acatinon** [comment]
@olipoh Yes, you are right, rotations set with the editor wasn't applied on physics object. I've just pushed a fix.

**Comment by acatinon** [comment]
I realize this PR is all wrong. I consused box2d origin and box2d center of mass.

In the editor, rotations seems to be centered on the object origin (size divided by 2) while in a overlap game (before my PR), origin of physics object were at the bottom left corner (this is easily noticable in @olipoh first video).

All I have to do is make origin of physics object at runtime match the object size divided by 2. Center of mass is a different feature that has nothing to do with all this !

I will fix this PR with another push soon.

**Comment by acatinon** [comment]
Ok, this should work fine now.

**Comment by olipoh** [comment]
Yes !!!

I made tests with different scenes, and the problems are solved. I'm impressed :-).

But actually, there is a slight difference. The objects are slower with your fix, as if the gravity were not the same. Maybe the problem was before your fix, I don't know.

If you want videos before and after the fix, just tell me.

PS : are you french ?

**Comment by acatinon** [comment]
Yes the objects are slower now, there was a bug I fixed in the commit a35751648449a78d768814de3c3619a7405dc629.

PS : Yes, I'm french !

**Comment by olipoh** [comment]
Alright. It works, it's wonderful. Thank you.

PS : would it be possible to speak privately ? olivier.hopp@gmail.com (french too).

**Comment by azakhary** [comment]
big thanks for taking on this guys! is it test-worthy at this point? also can you clamp the commits?

**Comment by olipoh** [comment]
As for me, the tests are conclusive, but I didn't test everything (and I won't have time next days).

As I'm a bit new on git, I don't understand "clamp the commits"...

**Comment by acatinon** [comment]
@azakhary Yes, I think it is ok for testing.

I don't understand "clamp the commits" either, do you want I merge all the commits in one ?

**Comment by azakhary** [comment]
crap I mean "squash" not clamp. sorry. As PR is done by @acatinon same use has to squash all 5 commits into one commit so we can merge.  There is bunch of stack-overflow answers on how to squash many commits in one.  This is just to keep repo "clean"

**Comment by acatinon** [comment]
Squash done !

**Comment by azakhary** [comment]
Thanks! we'll get back to this at the morning, it's a bit sleepy time here :))

**Comment by olipoh** [comment]
I have one question. When you merge a PR, what should I do in gradle ? Give another overlap runtime version name ? If yes, which one ? (ok it's more than one question).

**Comment by azakhary** [comment]
nope, it's going to be part of 0.1.2-SNAPSHOT
when I merge, I will then build a new jar to maven central, and a gradle refresh will do it. (sometimes you need to clear caches)

**Comment by olipoh** [comment]
Don't you think it may be a problem for bug that had a work around ? Just an example : if you merge PR 87, the gravity will be managed differently (as it seems there was a problem before). So people won't have the choice to keep their runtime, they will have to change the gravity value to have the same results / behaviors. Of course this is just an example with easy mandatory tuning. But it could be tricky for some other fixes...
I'm just asking, not trying to teach you anything :-) I'm learning...

**Comment by datscharf** [comment]
Hi there, 

I am very excited about these fixes good job to you all! Hope you don't think I am too impatient :-) but when will these changes become available in a new 0.1.2-SNAPSHOT?

Best regards
Martin

**Comment by azakhary** [comment]
I am horrible person I know :)))

Okay, done, tested, merged, and snapshot baking initiated. It'll be there in 10 minutes or so.

**Comment by acatinon** [comment]
Thanks!

**Comment by datscharf** [comment]
Damn that was quick! Thanks a lot!!  :D

**Pull request merged**
